version: 2
updates:
- package-ecosystem: docker
  directory: "/jenkins-slave"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  reviewers:
  - timurgaleev
  assignees:
  - timurgaleev
